kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: asd
  labels:
    app: mysql
  annotations:
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-3306
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30947
  selector:
    app: mysql
  clusterIP: 10.233.52.249
  clusterIPs:
    - 10.233.52.249
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
