#!/bin/bash

lsb_functions="/lib/lsb/init-functions"
if test -f $lsb_functions ; then
  . $lsb_functions
else
  init_functions="/etc/init.d/functions"
  if test -f $init_functionss; then
    . $init_functions
  fi
  log_success_msg()
  {
    echo " SUCCESS! $@"
  }
  log_failure_msg()
  {
    echo " ERROR! $@"
  }
fi

function usage(){
  echo "Usage: $0 {start|stop|restart}"
  exit 1
}

function start() {
    service mysql start
    sleep 1
    if [ `netstat -tunlp|grep mysql|wc -l` -ge 1 ]
      then
        log_success_msg "mysql is started."
      else
        log_failure_msg "mysql isn't started."
    fi
}

function stop() {
    killall mysqld &>/dev/null
      sleep 1
      if [ `netstat -tunlp|grep mysql|wc -l` -eq 0 ]
        then
            log_success_msg "mysqld is stopped."
      else
        log_failure_msg "mysqld isn't stopped"
      fi
}

function restart() {
    killall rsync
      sleep 1
      killpro=`netstat -tunlp|grep mysql|wc -l`
      service mysql start
      sleep 1
      startpro=`netstat -tunlp|grep mysql|wc -l`
      if [ "$killpro" -eq 0 -a "$startpro" -ge 1 ]
          then
            log_success_msg "Rsyncd is restarted."
          else
            log_failure_msg "Rsyncd isn't restarted."
      fi
}

function main() {
    if [ "$#" -ne 1 ]
      then
        usage
    fi

    if [ "$1" = "start" ]
      then
        start
    elif [ "$1" = "stop" ]
      then
        stop
    elif [ "$1" = "restart" ]
      then
        restart
    else
      usage
    fi
}


# 调用程序入口函数
main $*



















