#!/bin/bash
# author:chaos
# -ne if 条件的不等于，$# 返回传递给脚本的参数个数$0取得脚本文件名
if [ "$#" -ne 1 ]
    then
        echo "Usage: $0 {start|stop|restart}"
        exit 1
fi

if [ "$1" = "start" ]
    then
        /usr/bin/rsync --daemon
        sleep 1
        if [ `netstat -tunlp|grep rsync|wc -l` -ge 1 ]
            then
                echo "Rsync is started."
                exit 0
        fi
elif [ "$1" = "stop" ]
    then
        killall rsync &>/dev/null
        sleep 1
        if [ `netstat -tunlp|grep rsync|wc -l` -eq 0 ]
            then
                echo "Rsync is stopped."
                exit 0
        fi
elif [ "$1" = "restart" ]
    then
        killall rsync
        sleep 1
        killpro=`netstat -tunlp|grep rsync|wc -l`
        /usr/bin/rsync --daemon
        sleep 1
        startpro=`netstat -tunlp|grep rsync|wc -l`
        if [ "$killpro" -eq 0 -a "$startpro" -ge 1 ]
            then
                echo "Rsyncd is restarted."
        fi
else
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi





























































