apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      command:
        - redis-server
        - "/redis-master/redis.conf"  #指的是redis容器内部的位置
      ports:
        - containerPort: 6379
      volumeMounts:                   #持久卷
        - mountPath: /data
          name: data
        - mountPath: /redis-master
          name: config111
  volumes:
    - name: data
      emptyDir: {}
    - name: config111
      configMap:
        name: redis-conf222
        items:
          - key: redis.conf333
            path: redis.conf